FROM node:current-slim

WORKDIR /client

COPY package*.json ./
# RUN is used to execute commands during the build process of a Docker image
RUN npm install

COPY . /client/

EXPOSE 3000
# CMD is used to specify the default command to run when a Docker container is started from the image
CMD ["npm", "run", "dev"]