---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: todo-app
spec:
  selector:
    app: todo-frontend
  ports:
    - name: todo-app
      port: 3000
      targetPort: 3000
  type: LoadBalancer
